# Default to dev profile if not specified
spring.profiles.active=${ENVIRONMENT}

graphql.endpoint=${GRAPHQL_URL}
graphql.apiKey=${GRAPHQL_API_KEY}
# Common settings for all environments
spring.application.name=hotel-property-service
spring.jackson.time-zone=UTC
server.servlet.context-path=/
server.error.include-message=always
api.base.url=${API_URL_REVIEW}

# Time Zone Configuration
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Mail Server Properties
spring.mail.host=${HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP Configuration
otp.expiry.minutes=5
otp.max.attempts=3

# JWT Configuration for AWS Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_IGHZ9OObg
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_IGHZ9OObg/.well-known/jwks.json

# Actuator Properties
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG
